### ISSUE TITLE
Candidates for removal/improvement?

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/scpcb#104]
I doubt removing all of the SCPs in this list would be a great idea, but I'll just list the crappier ones that we should consider removing to make room for greater additions:

- SCP-178: It poses no immediate threat or benefit to the player, so it loses all of its value after the first playthrough. Ultimately, all it does is give you a way to kill yourself, which is not what a player should really want.
- SCP-205: The animations are garbage, the room has random bits of geometry sticking out of weird places, and it has the same issues as 178.
- SCP-372: Requires the player to actively interact with it, poses no threat to the player and doesn't even work as a good jumpscare after a while.
- SCP-513: Same problems as 372.
- SCP-714: Far too few uses to justify the handicaps it applies.
- SCP-1025: Same problems as 178. It's arguably less interesting than any other SCP in the game.
- SCP-1048-A: Its event is bland and sorta broken. Maybe it could be reimplemented as a roaming enemy instead?
- SCP-1499: Its implementation is buggy as hell, and unlike 714 it provides no handicap making it far too overpowered. The fact that it can be used to avoid MTFs or any roaming threat makes it OP to the point where it breaks the entire 'scare factor' of encountering a threat.

**Comment by notemissary** [comment]
I think that removing any of the SCP's is a bad idea just because they do exist in wiki, so why removing them? But that's ok to improve some, although it should be according to the SCP lore.

**Comment by juanjp600** [comment]
See https://github.com/juanjp600/scpcb/issues/56

Being good for the wiki != being good for SCPCB

**Comment by notemissary** [comment]
How do you determine whether the object is good for the game or not? I'm playing the game to explore the SCP objects, not just to get to the end, so I think that keeping all the objects would be great.

**Comment by CommanderMark** [comment]
> I'm playing the game to explore the SCP objects, not just to get to the end
If we're talking a "walk around the Foundation" simulator then sure, but this is suppose to be a horror game. It should targeting an audience that wants to play a horror game, not a sim.

**Comment by juanjp600** [comment]
I don't believe the game should be designed around exploration just for the sake of it. There should always be an incentive or a driving force behind every action the player takes, which boils down to making most things useful, necessary or an active threat to the player. Anything that doesn't fit this description is at worst confusing to a player who doesn't know any better and wastes their time or ruins their save by interacting with things that are not at all relevant to the end goal.

On top of that, some of the things that the player can use to their advantage (and even some of the threats) have serious balancing issues, which is a consequence of not putting enough effort in making sure that everything fits in with the rest of the game, and only adding stuff in as fanservice. As such, all you get is a frustrating game, which detracts from the fun, and possibly the horror.
