### ISSUE TITLE
173opt.b3d Error! Urgent!

### ISSUE THREAD

**Issue by SweetPhoenixGaming** [Regalis11/scpcb#105]
Hi, I was adding some details to a mod of mine I made for SCP Containment Breach, I use the B3D to RMESH conversion application and now my game has stoppped working. Basically, when it has reached 40% loaded, it stops and it say "GFX/map/173opt.b3d not found" so I toom a look and found the file but it was a .rmesh file and not a .b3d file. If anyone can send me a copy of their 173opt.b3d file or show me how to fix this, I will be more than happy to talk!

**Comment by VaneBrain** [comment]
Is there a reason you used this conversion?

**Comment by YoshiRulz** [comment]
That file [doesn't exist](https://github.com/Regalis11/scpcb/search?q=filename:opt.b3d) and, if it did once exist, [hasn't since v1.3](https://github.com/Regalis11/scpcb/tree/v1.3/GFX/map).

**Comment by theOneTrueFunniBoi** [comment]
You will need to restore your Data\rooms.ini file to one from an earlier version of your mod, or from stock scpcb 1.3.11.
