### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by secondfry** [Regalis11/scpcb#115]
It's clear that SCP:SL is violating CC BY-SA 3.0 – while being a derivative work and clearly stating "based on SCP:CB", it uses it's own private EULA.

Is any action going to be taken upon this?
Could it be that license would be switched to CC BY?

**Comment by CommanderMark** [comment]
I'm not really sure this is the right place to bring this up. A better thing to do would be to make the Foundation's licensing team aware of this: http://www.scp-wiki.net/licensing-guide

**Comment by secondfry** [comment]
Routed info to SCP Foundation Licensing Team, thank you.
