### ISSUE TITLE
Is this like it should be?

### ISSUE THREAD

**Issue by fgRuslan** [Regalis11/scpcb#118]
There are some green dots in the launcher window, but in the game everything is fine.

**PC specs**:
AMD FX-6300
AMD Radeon RX550 2GB(Driver version: Adrenalin 19.3.3)
8GB RAM
Windows 7 x64 Ultimate

![изображение](https://user-images.githubusercontent.com/11362683/61374683-a4d4f200-a8a5-11e9-9a71-d3f7a34957a1.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/scpcb/commit/6303a175725f341511dd0b6637dd5760e1e1e833
