### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Hedreon** [Regalis11/scpcb#126]
I tried clicking on the "Run" button in Blitz3D but the warning showed up and said: _Function 'fsound_init' not found_

How do I fix it?

_(Yes, I'm new to compiling Blitz3D games)_

More details _(To try to make it easier to solve this)_:

- OS: _Windows 10 Home_

- Compiler: _Blitz3D v1.108_

- Source Location: _C:\Users\User\Desktop\scpcb-v.1.3.11_

- Location of warning: _C:\Users\User\Desktop\scpcb-v.1.3.11\FMod.bb_

**Comment by Saalvage** [comment]
You need to copy all .decls files into your b3d userlibs folder, as well as replace your b3d bin directory by the one in the mavless_bin.zip folder.

**Comment by Hedreon** [comment]
YESSSS!!!!!!!!!!!!!! TYSM!!!!!!! FINALLY!! GOT IT WORKING!! THANKS!
