### ISSUE TITLE
How do i edit the game

### ISSUE THREAD

**Issue by MXofficial** [Regalis11/scpcb#127]
I am making a mod and i wanna change the text on the menu but i can't. What should i do? I did install Blitz3D and did all the  stuff the instructions told me

**Comment by Saalvage** [comment]
Are you running the game via Blitz3D?

**Comment by MXofficial** [comment]
well i got Blitz3D installed but i did not open it with Blitz3D and how do you do that?

**Comment by MXofficial** [comment]
> Are you running the game via Blitz3D?

well i got Blitz3D installed but i did not open it with Blitz3D and how do you do that?

**Comment by Saalvage** [comment]
I'm sorry for not getting back to you sooner, but this is really not the place for such discussion, check out the Undertow Discord (https://discord.gg/undertow) and I'll happily help you out.
