### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by WhenDayBreaks** [Regalis11/scpcb#128]
CC should *not* be used on software. GNU GPL is compatible with CC, therefore change to that.

**Comment by WhenDayBreaks** [comment]
It seems that you are not here.

**Comment by Bluscream** [comment]
?

**Comment by Bluscream** [comment]
[![](url)](![url](

> url

___

___
## **____**

### - 1. ### ## # ## ### ~~__**~~))~~**__~~

**Comment by Phoenix1747** [comment]
> CC should _not_ be used on software.

If you're using SCP things you need the CC license.

>  GNU GPL is compatible with CC, therefore change to that.

Not gonna happen...
