### ISSUE TITLE
mavless_bin.zip

### ISSUE THREAD

**Issue by hlpdev** [Regalis11/scpcb#245]
Hey Regalis, sorry to open an issue, but I was wondering if you had the source code to the files in the mavless_bin.zip file because I am trying to port Blitz3D over to DirectX 9 but I want the game to be compatible with SCP: Containment Breach. Is there any way you could either send the source or direct me to where I could find it? Thanks.

**Comment by Veinhelm** [comment]
https://github.com/juanjp600/blitz3d/
