### ISSUE TITLE
Game Crashes when alt tabbing while the game is fullscreen.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [Regalis11/scpcb#250]
Title explains bug.

**Comment by VaneBrain** [comment]
The only thing I can suggest is to play in Borderless Windowed mode.

**Comment by theOneTrueFunniBoi** [comment]
Does the game pause itself when you alt tab from it?

**Comment by theOneTrueFunniBoi** [comment]
Scratch that, just tested and it does not.

**Comment by theOneTrueFunniBoi** [comment]
Well then, not much to do
