### ISSUE TITLE
Remnants of removed SCP-066 achievement in dev branch

### ISSUE THREAD

**Issue by ChronoQuote** [Regalis11/scpcb#251]
When accc960 removed the new SCP-066 achievement from the dev branch, a couple pieces of it remained, including the achievement icon (GFX\menu\achievements\Achv066.jpg), and the code that triggers the achievement:
https://github.com/Regalis11/scpcb/blob/6933225b0cd5aa00a8345c9c0f7fe914d94312f3/NPCs.bb#L3920-L3923
Since `Achv066` no longer exists, it'll have a default value of 0, which is the ID of the SCP-008 achievement. So currently, in the dev branch, approaching 066 will trigger 008's achievement.

This isn't a huge deal since you should already have 008's achievement by the time you can even meet 066, but it's an easy fix. Alternatively, one of either #200 or #258 could be merged.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/scpcb/commit/75eee99feeea9023f54635c50eeaddcf38a727ca
