### ISSUE TITLE
CBRE: Error: Value Cannot Be Null

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [Regalis11/scpcb#254]
I get this at random and can't fix it.
After getting this error, no models will be exported at all.
Heres the full message:
![image](https://github.com/Regalis11/scpcb/assets/112577221/d33842a6-58c0-4103-a1b7-3d6363808d6b)

**Comment by VaneBrain** [comment]
You should report it here: https://github.com/AnalogFeelings/cbre-ex

**Comment by theOneTrueFunniBoi** [comment]
I didn't know cbre-ex exsisted! I'll try it out instead of normal cbre.
