### ISSUE TITLE
I started using Blitz3D TSS but everything is breaking.

### ISSUE THREAD

**Issue by theOneTrueFunniBoi** [Regalis11/scpcb#259]
I Just switched to b3d tss but stuff is breaking like hell, theres small things like the engine renaming the INFINITYY Variable to its own, causing errors. Then the medium things like loadfont only wanting 2 params. Then a b3d array error in mapsystem.bb. Why is this happening, it wasn't like this with normal b3d.

**Comment by ChronoQuote** [comment]
SCP - Containment Breach runs on Blitz3D, not Blitz3D TSS, so of course things broke. Blitz3D TSS is a different game engine made for SCP: Nine-Tailed Fox.

**Comment by Jabka666** [comment]
> SCP - Containment Breach runs on Blitz3D, not Blitz3D TSS, so of course things broke. Blitz3D TSS is a different game engine made for SCP: Nine-Tailed Fox.

Ultimate Edition Reborn also uses Blitz3D TSS

**Comment by theOneTrueFunniBoi** [comment]
Yeah good point, I thought it was a rebuild “enhanced” version or something, but I guess I was wrong. Thanks for clarifying.
