### ISSUE TITLE
Buttons in room2closets are floating.

### ISSUE THREAD

**Issue by CommanderMark** [Regalis11/scpcb#47]
The buttons for the door found in the middle of room2closets are floating a few units off the wall.

I'm not sure if there is some sort of function I can use to reposition the buttons on doors so posting this here.

**Comment by juanjp600** [comment]
MoveEntity door\buttons[0],0.0,0.0,0.01

Put something like this under room2closets' case in FillRoom, MapSystem.bb

**Comment by CommanderMark** [comment]
Fixed.
