### ISSUE TITLE
Wanting to have a play around with it, but can't launch any of it - User Lib not found, fmod not found, bb_fmod not found etc.

### ISSUE THREAD

**Issue by JakesCode** [Regalis11/scpcb#77]
Am I missing something? I've downloaded Blitz3D, but it's looking for 'bb_fmod.dll' which can't be found anywhere in the repo? I went to the FMOD website and downloaded it but it still can't find anything.
If I go into Blitz3D and try to run it it highlights the 'FSOUND' function call and says it can't find that function.

I'm on Windows 8 if that helps.

**Comment by VaneBrain** [comment]
Be sure that you put decls files in Blitz3d/uselibs

**Comment by JakesCode** [comment]
Ah, yes. that's solved it. Thanks @VaneBrain
