### ISSUE TITLE
MTF Announcer Sound Bug

### ISSUE THREAD

**Issue by AlyMar1994** [Regalis11/scpcb#84]
Whenever the MTF spawn and the announcer announces their arrival, 4/5 times (in my experience) he will get cut off around a quarter way through his speech.

**Comment by ENDSHN** [comment]
Do you have a seed with this error?
Maybe I could provide a fix if it might actually be seed depending.

**Comment by VaneBrain** [comment]
It happens when Gate A spawns near Tesla. And to prevent the sound overlapping it stops prev. sound and start new one

**Comment by AlyMar1994** [comment]
Weird, because when it happened to me, the announcer cut off, then after a 20 second delay, the voice line saying one of the gate's elevators were out played. Another 10 seconds later, the tesla request.

Maybe something can be done, so all files can play out? Maybe prioritize some tracks over others, like a list?
