### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by SleepyMode** [Regalis11/scpcb#89]
It is impossible to compile without 90% the source code being gone.
None of the guides provide an accurate and updated version of how to compile, either.

How is it done???

**Comment by AgentParadox** [comment]
I think you mean "_With_ 90% of the source code being gone".
And you can compile: just re-compile main.bb, the other bb files are attributed to it, so they'll automatically update when you do.

**Comment by SleepyMode** [comment]
No. The code has errors, so you cant compile.

**Comment by Voros2** [comment]
Do you have the correct libraries set up?

**Comment by SleepyMode** [comment]
Yep.

**Comment by Voros2** [comment]
What exactly are the errors?

**Comment by Regalis11** [comment]
Without further info there's not much we can do to help. I'm guessing some of the required userlibs haven't been installed.
