### ISSUE TITLE
room2sl

### ISSUE THREAD

**Issue by juanjp600** [Regalis11/scpcb#94]
Everything about room2sl is wrong.

**Comment by VaneBrain** [comment]
Thanks for pointing out what's wrong! We will fix it in next update ;)

**Comment by AlyMar1994** [comment]
I second this issue.

**Comment by ENDSHN** [comment]
room2sl is very broken as of now, hopefully I will be able to fix it for 1.3.10. The biggest issue as far as I can tell is the camera system which doesn't work properly.
Altough everything else about it really needs to be changed entirely to make it work properly without issues.

**Comment by juanjp600** [comment]
See #102
