### ISSUE TITLE
Teamspeak SDK Implementation

### ISSUE THREAD

**Issue by Bluscream** [Regalis11/scpcb#97]
Since this game is powered by Unity i would love to see Teamspeak's SDK integrated for LAN coop or just talking to another random player and maybe helping each other out :)

http://teamspeak.com/en/downloads.html#sdk

**Comment by Regalis11** [comment]
Wrong repo? :) Neither SCP-CB or Barotrauma are powered by Unity.

**Comment by Bluscream** [comment]
Em, what engine then? :O

**Comment by Regalis11** [comment]
Blitz3D. The game doesn't have any sort of multiplayer features either so I'm not sure what would be the benefit of Teamspeak integration.

**Comment by Bluscream** [comment]
Oh i thought Blitz3D was a mapeditor like hammer ^^
